name: Deploy to Google Cloud

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Set up Podman
        run: |
          sudo apt-get update && sudo apt-get install -y podman

      - name: Build backend image
        run: |
          podman build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/server ./server

      - name: Push backend image
        run: |
          podman login -u _json_key --password-stdin https://gcr.io <<< "${{ secrets.GCP_SA_KEY }}"
          podman push gcr.io/${{ secrets.GCP_PROJECT_ID }}/server

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy server \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/server \
            --add-cloudsql-instances ${{ secrets.GCP_SQL_CONNECTION_NAME }} \
          host: '/cloudsql/galvanic-vim-464504-n5:us-central1:medicine-shop-db',
            --set-env-vars DB_HOST=/cloudsql/${{ secrets.GCP_SQL_CONNECTION_NAME }},DB_NAME=medicine_shop,DB_USER=medicine-shop-user,DB_PASSWORD=${{ secrets.DB_PASSWORD }},NODE_ENV=production \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated

  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    needs: build-and-deploy-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build frontend
        run: |
          cd client
          npm install
          npm run build

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Upload frontend to GCS
        run: |
          gsutil -m rsync -r client/build gs://$GCP_BUCKET_NAME
          gsutil web set -m index.html -e index.html gs://$GCP_BUCKET_NAME
          gsutil iam ch allUsers:objectViewer gs://$GCP_BUCKET_NAME